# Generated by Django 3.1.3 on 2020-12-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=20)),
                ('Gender', models.CharField(default='male', max_length=10)),
                ('Region', models.CharField(default='earth', max_length=20)),
                ('Nickname', models.CharField(default='fresh', max_length=20)),
                ('Avatar', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=40)),
            ],
        ),
    ]
