# Generated by Django 3.1.4 on 2020-12-28 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Description',
        ),
    ]
