# Generated by Django 3.1.4 on 2020-12-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('RecordID', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('Type', models.CharField(max_length=20)),
                ('Time', models.CharField(max_length=20)),
                ('Ownusername', models.CharField(max_length=20)),
                ('Amount', models.IntegerField()),
                ('Comment', models.CharField(max_length=20)),
            ],
        ),
    ]
